### ISSUE TITLE
Thumbnail for the card display

### ISSUE THREAD

**Issue by Sulphinx** [VertisanPRO/tracker#11]
### Product

Quantum

### Describe the solution you'd like

Optional to add a card to thumbnail for each server, it should be effected by its egg, so if its minecraft, there is a minecraft thumbnail etc.
![https://cdn.padow.ru/ThK3f](https://cdn.padow.ru/ThK3f)

**Comment by VanillaChan6571** [comment]
Quantum v0.3.0 removed this feature?
