### ISSUE TITLE
The server's text doesn't fit

### ISSUE THREAD

**Issue by Niclas-M1** [VertisanPRO/tracker#15]
### Product

Quantum

### Describe the issue
<img width="1077" alt="image" src="https://github.com/VertisanPRO/tracker/assets/60582586/cdb268a3-e70c-451c-8612-e290e47b175d">

### Product Version

0.1.0

### Pterodactyl Panel Version

1.11.5

### To Reproduce

Open the Server Overview as a User

**Comment by PadowYT2** [comment]
Not sure what to do - [Message Link](https://canary.discord.com/channels/760945720470667294/1192242317541781504/1193867225329840190)

**Comment by Niclas-M1** [comment]
Maybe let the Icon be at a fixed. Size, but change the Text automatically to fit if in, if it wouldn't fit with the normal Text Size.

**Comment by PadowYT2** [comment]
![https://cdn.padow.ru/zPrRd](https://cdn.padow.ru/zPrRd)
