### ISSUE TITLE
Some Features from our old Stelar Theme

### ISSUE THREAD

**Issue by Niclas-M1** [VertisanPRO/tracker#18]
### Product

Quantum

### Describe the solution you'd like

We had the [Stelar Theme](https://builtbybit.com/resources/stellar-theme-latest-pterodactyl.22243/) before (it had some nice Features.
> Would it be possible to integrate some of them also into Quantum?

Here some Features:
1. fixed Header, where you can always see and manage (start, stop and kill) the Server
![image](https://github.com/VertisanPRO/tracker/assets/60582586/5ee0a73c-5bcb-486f-9e82-971a5a666b48)
![image](https://github.com/VertisanPRO/tracker/assets/60582586/317bb01f-9b5b-42d6-9312-1b22768a2e06)
![image](https://github.com/VertisanPRO/tracker/assets/60582586/00a8e052-027c-489e-a1ea-9d916bfd5a62)

2. Quantum already has, but a few tweaks would be nice:
And I would apreacheate it, if a second Spacer Line would be aded under the "Dashboard" Line to separate the Dashboard from the Server Sited, like done with the Account Stuff
![image](https://github.com/VertisanPRO/tracker/assets/60582586/c486c604-9c74-4fe2-9266-6fe242511f46)
- And it would be really Nice, if we could change the Icons for the Page Icons in like a GUI or a Line to type it in directly.
- And would it be possible to give multiple options for the Update Animation for the Stat Graphs (because some People find it nice like it is, but others find it disturbing and would rather use a animation, where it just lines to the left.

**Comment by PadowYT2** [comment]
You must actually write and explain the features instead of saying "copy from stellar"

**Comment by Niclas-M1** [comment]
@PadowYT2 I changed it, could you have a look please again?

**Comment by Niclas-M1** [comment]
thx
