### ISSUE TITLE
Fixed Header

### ISSUE THREAD

**Issue by PadowYT2** [VertisanPRO/tracker#20]
### Product

Quantum

### Describe the solution you'd like

A fixed header that will be on every single server page, like on Stellar
![image](https://github.com/VertisanPRO/tracker/assets/71085027/c42226fc-6304-4803-84c8-19cda3cca5ee)

### Additional context

Suggested by @Niclas-M1 (VertisanPRO/tracker#18)

**Comment by PadowYT2** [comment]
Need an approval
![https://cdn.padow.ru/J0DfD](https://cdn.padow.ru/J0DfD)
![https://cdn.padow.ru/jLAXs](https://cdn.padow.ru/jLAXs)

**Comment by Niclas-M1** [comment]
Looks stunning
