### ISSUE TITLE
Add the "#Short-ID" of the Server to the Server-Cards or somewhere els please

### ISSUE THREAD

**Issue by Niclas-M1** [VertisanPRO/tracker#33]
### Product

Quantum

### Describe the solution you'd like

It would be easier, if the Short-ID of the Server would somewhere be visible for the Users with the "#" to get easier in touch with the User in the Support.
<img width="1238" alt="image" src="https://github.com/VertisanPRO/tracker/assets/60582586/ef8870d8-791f-4151-a69b-ab3fe83ed4d9">

**Comment by PadowYT2** [comment]
Where exactly though?
