### ISSUE TITLE
Show "Suspended" on suspended Servers

### ISSUE THREAD

**Issue by Niclas-M1** [VertisanPRO/tracker#36]
### Product

Quantum

### Describe the solution you'd like

would it be possible to have a better design of the Service-card if the Server is suspended?
<img width="608" alt="image" src="https://github.com/VertisanPRO/tracker/assets/60582586/aad6d5f6-ba24-4609-a60b-61c9111c0d04">

**Comment by PadowYT2** [comment]
Where exactly?

**Comment by Niclas-M1** [comment]
maybe a yellow Border around the Server?
(around the Server-Card on the Server overview / Main-Page)

**Comment by RobertGreen-25** [comment]
Do you mean something like this.

![image](https://github.com/VertisanPRO/tracker/assets/142682946/9a493b35-a8c6-480c-9f02-8b4895034c5e)

**Comment by PadowYT2** [comment]
> Do you mean something like this.
> 
> ![image](https://private-user-images.githubusercontent.com/142682946/302129781-9a493b35-a8c6-480c-9f02-8b4895034c5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNzcwNjcsIm5iZiI6MTcwNzA3Njc2NywicGF0aCI6Ii8xNDI2ODI5NDYvMzAyMTI5NzgxLTlhNDkzYjM1LWE4YzYtNDgwYy05ZjAyLThiNDg5NTAzNGM1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQxOTU5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDdhMmVmNmRiNThlN2FmMzA0OTQ4Y2M0OTkzOTAzNjY2Yzc4NDU3M2YxYWE1ZWRkZGRkOGY2NzY4NjJlZjRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.guORgIhr6N1n_yj_pyScHsRAItJ6Ap7br1NlSy3Pjuw)

That doesn't look too great, but I understood what he said
