### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by LucaBrecher** [VertisanPRO/tracker#38]
### Product

Quantum

### Describe the issue

There are a few buttons which aren't working. For example:

- UserAPI (https://paneldomain.com/account/api)
- Renaming a file the ,,rename'' button

### Product Version

0.1.2

### Pterodactyl Panel Version

1.11.5

### To Reproduce

Go to https://paneldomain.com/account/api and click on ,,create''.
Try to rename a file and click on ,,rename''.

### Expected Behaviour

The buttons should work. ;)

**Comment by PadowYT2** [comment]
Already fixed, refer to support channel
