### ISSUE TITLE
Suggestions for Unix

### ISSUE THREAD

**Issue by infnibor** [VertisanPRO/tracker#40]
### Product

Unix

### Describe the solution you'd like

Adding the ability to change the default avatar (Gravatar) to your own and adding to the "Account" tab the ability to change the Name and Surname, previously set during registration, because for now it can only be done from the Pterodactyl admin panel, but not in the user interface itself. 

### Describe alternatives you've considered

Possible, I also suggest adding the ability to change the color of buttons in the panel or the ability to sort servers into folders, tiles, or swap places

### Additional context

![image](https://github.com/VertisanPRO/tracker/assets/156368035/2d8273d1-f9a6-4008-8e72-61da824eb851)
![image](https://github.com/VertisanPRO/tracker/assets/156368035/57a4a43f-e46d-4534-95db-532051be0709)
![image](https://github.com/VertisanPRO/tracker/assets/156368035/46c78f47-2b7a-4e6f-b0e8-3e4e1fc4b202)
![image](https://github.com/VertisanPRO/tracker/assets/156368035/b1b08355-4a5f-46cb-9a6b-4c212d45aad4)

**Comment by PadowYT2** [comment]
> Adding the ability to change the default avatar (Gravatar) to your own and adding to the "Account" tab the ability to change the Name and Surname, previously set during registration, because for now it can only be done from the Pterodactyl admin panel, but not in the user interface itself.

This is really hard to do and will not be done

> Possible, I also suggest adding the ability to change the color of buttons in the panel

You would need to use custom css

> the ability to sort servers into folders, tiles, or swap places

This is outside of Unix and must be done via an addon
