### ISSUE TITLE
Country Reverts to Asland  Islands

### ISSUE THREAD

**Issue by edwynmoss** [VertisanPRO/tracker#41]
### Product

Quantum

### Describe the issue

No matter the country chosen in the Client Area or choosing within the admin for the client. The countries bound to the profile reverts back to  Asland Islands. 

Attempted in Client Area as well as Admin on behalf of client 

![image](https://github.com/VertisanPRO/tracker/assets/106533684/f3d27e88-2b24-440d-a6e2-22bc345fe2cf)

### Product Version

2.1.0

### Pterodactyl Panel Version

1.11.7

### To Reproduce

Go to your client settings, and choose the location country, attempt to save the settings and the issue should be reproduced. 

![image](https://github.com/VertisanPRO/tracker/assets/106533684/ab59f800-8da1-45e9-a667-4c8ed4fd31ae)

### Expected Behaviour

For my chosen country to be saved as selected

### Screenshots

![image](https://github.com/VertisanPRO/tracker/assets/106533684/0c179649-0513-4cae-aa83-b458544808e3)

![image](https://github.com/VertisanPRO/tracker/assets/106533684/1abda43f-feb0-4cba-9c3c-8d8cfa60ddde)

**Comment by purejosh** [comment]
Can confirm this behavior.

**Comment by purejosh** [comment]
You could've transferred this issue to the right tracker, you know...

**Comment by PadowYT2** [comment]
> You could've transferred this issue to the right tracker, you know...

You know that I can't because WemXPro and VertisanPRO are 2 different organizations

**Comment by purejosh** [comment]
I guess I was wrong. I thought you could cross org them. My apologies. 

@edwynmoss, can you report this in the [WemX github](https://github.com/WemXPro/tracker/issues)?
