### ISSUE TITLE
Multiple images for a background

### ISSUE THREAD

**Issue by PadowYT2** [VertisanPRO/tracker#6]
From tracker created by [PadowYT2](https://github.com/PadowYT2): WemXPro/tracker#274  

### Product

Unix

### Describe the solution you'd like

So you can choose what image do you want for Dark/White mode

### Additional context

Suggested by @Groot239

**Comment by PadowYT2** [comment]
+1

**Comment by Sulphinx** [comment]
Can this be added to the quantum label? 😄
