### ISSUE TITLE
Make NodeJS utils

### ISSUE THREAD

**Issue by PadowYT2** [VertisanPRO/tracker#7]
### Product

Quantum

### Describe the solution you'd like

The installer should auto-install NodeJS and if needed run `export NODE_OPTIONS=--openssl-legacy-provider` if the NodeJS version is >= v17

**Comment by Pvpsmash** [comment]
how to manually install without autoinstaller or not possible yet?

**Comment by PadowYT2** [comment]
> how to manually install without autoinstaller or not possible yet?

This isn't the place to ask these questions
