### ISSUE TITLE
Card display wrong margin/size

### ISSUE THREAD

**Issue by Sulphinx** [VertisanPRO/tracker#9]
### Product

Quantum

### Describe the issue

One of my servers on the card display is bigger than the other one, you can see on the image.

### Product Version

0.1.0

### Pterodactyl Panel Version

1.11.5

### Expected Behaviour

Well the cards should be lined up and not be wrongly placed.

### Screenshots

![Screenshot 2024-01-06 205716](https://github.com/VertisanPRO/tracker/assets/94517012/2e0dbfad-dfd2-4896-a6c5-acbfb40f7727)

**Comment by Niclas-M1** [comment]
same here, but also the Connection Data of the Servers is cut off
<img width="1077" alt="image" src="https://github.com/VertisanPRO/tracker/assets/60582586/cdb268a3-e70c-451c-8612-e290e47b175d">

**Comment by PadowYT2** [comment]
> same here, but also the Connection Data of the Servers is cut off <img alt="image" width="1077" src="https://private-user-images.githubusercontent.com/60582586/294717471-cdb268a3-e70c-451c-8612-e290e47b175d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NzY1OTAsIm5iZiI6MTcwNDU3NjI5MCwicGF0aCI6Ii82MDU4MjU4Ni8yOTQ3MTc0NzEtY2RiMjY4YTMtZTcwYy00NTFjLTg2MTItZTI5MGU0N2IxNzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDIxMjQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmYTIwODA2NDdhN2Y0Y2Y0N2E4NjQ4OWQ2MzNkYjBjMmM5YjFiZTgwYzRmZmU5YjdkNmQ4NTVhNTEyNDgzZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bHZxYrTDUkY-EAZEKMOu-5IP4CdwgHKylX0XVT8cb0k">

Can you make a different issue please?

**Comment by PadowYT2** [comment]
![https://cdn.padow.ru/9ksAj](https://cdn.padow.ru/9ksAj)
